#
#  Base file for SolidSense provisioning V0.95
#
#  Copyright Sterwen-Technology/SolidRun 2019
#
#   that file provide the basic minimum configuration for Kura and all SolidSense services
#   It shall be located in /opt/SolidSense/config and named SolidSense-conf-base.yml
#
#   The customer specific configuration is located in /data/solidsense/config/SolidSense-conf-custom.yml
#   The combination of both files will be applied to the gateway
#
#   mini language
#
# Global variable definition
gateway:
    # if the gateway-id is set it will be used as is for all transport service
    # gateway-id: $SERIAL-NUMBER
    # here are all the default variable that are created implicitely
    # SERIAL-NUMBER     serial number of the gateway
    # PART-NUM          full part number including variant
    # MODEL-ID          product code
    # MODEL-NAME        Description of hardware configuration
    # FIRMWARE          Actual firmware running
    
    snapshot_0: snapshot_0.xml
    # mode can be normal or test. In test mode all files are generated in /temp directory
    mode: normal 
#
#
#  Services definition
#
services:

- service:
    # MQTT connection to Kapua
    type: KuraService
    name: KapuaMQTT
    state: active
    parameters:
        configuration: MqttDataTransport
    properties:
        broker-url: mqtt://kapua.solidsense.io:1883
        topic.context.account-name: SOLIDSENSE-NURSERY
        username: newborn-gw
        password: ^$SolidSense2019$
        client-id: $SERIAL-NUMBER
        
- service:
    # Data service (MQTT) parameters
    type: KuraService
    name: MqttData
    parameters:
        configuration: DataService
    properties:
        connect.auto-on-startup: true
        
- service:
    # NTP connection
    type: KuraService
    name: Clock
    parameters:
        configuration: ClockService
    properties:
        enabled: true

- service:
    # Local loop
    type: NetworkService
    name: lo
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    properties:
        config.ip4.status: netIPv4StatusEnabledLAN
        config.state: ACTIVATED
        
        
#
#  Default network configuration
#   WAN => Eth0 / DHCP
#   LAN => wlan0
#
- service:
    # Ethernet port
    type: NetworkService
    name: eth0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
    variables:
    properties:
        config.ip4.status: netIPv4StatusEnabledWAN
        config.dhcpClient4.enabled: true
        config.dhcpServer4.enabled: false
        config.autoconnect: true
        
#
#   WiFi configuration by default
#   Access point
#   HW mode=g. Higher mode not yet supported by KuraService
#
- service:
    type: WiFiService
    name: wlan0
    state: active
    parameters:
        configuration: NetworkConfigurationService
        prefix: net.interface.$service_name
        state: active
    variables:
        WPA_KEYMGMT: WPA-PSK
        WIFI_PASSWORD: testKEYS
        WPA_LEVEL: 2
        WPA_PAIRWISE: CCMP
        WIFI_MODE: g
        WIFI_CHANNEL: 5
        WLAN-INTERFACE: $service_name
        
    properties:
        config.wifi.mode: MASTER
        config.ip4.status: netIPv4StatusEnabledLAN
        config.wifi.master.mode: MASTER
        config.dhcpServer4.passDns: true
        config.wifi.master.securityType: SECURITY_WPA2
        config.wifi.master.ssid: $SERIAL-NUMBER
        config.wifi.master.passphrase: $WIFI_PASSWORD
        config.wifi.master.pairwiseCiphers: $WPA_PAIRWISE
        config.wifi.master.radioMode: RADIO_MODE_80211$WIFI_MODE
        config.ip4.address: 172.16.1.1
        config.dhcpServer4.rangeStart: 172.16.1.100
        config.dhcpServer4.rangeEnd: 172.16.1.115
        
#
#   Modem/GPS service
#
# activated when a modem is detected
#
#  Global variable created by the modem_gps service
#
#   MODEM_MFG   name of the manufacturer
#   MODEM_MODEL model name
#   MODEM_IMEI
#   MODEM_SIM_IN    true if a SIM is present, false otherwise
#

- service:
    type: ModemGps
    name: modem_gps
    state: auto
    parameters:
        system: modem_gps
        port: 20231
        address: 0.0.0.0
        modem_ctrl: /dev/ttyUSB2
        nmea_tty: /dev/ttyUSB1
        trace: info
        PIN: '0000'
        roaming: true
        operatorsDB: 'operatorsDB'
        start_gps: false