#
#  Test file for SolidSense provisioning
#
- service:
    type: KuraService
    name: KapuaMQTT
    parameters:
        snapshot: mqtt
    keywords:
        MQTT_BROKER: mqtt://kapua.solidsense.io:1883
        KAPUA_ACCOUNT: SOLIDSENSE-TEST
        KAPUA_USER: solidsense-internal
        KAPUA_PASSWORD: $SolidSense2019$

- service:
    type: PppService
    name: ppp0
    parameters:
        snapshot: net
        modem: EC25
    keywords:
        APN: orange
        APN_AUTH: PAP
        APN_USER: orange
        APN_PASSWORD: orange

- service:
    type: WiFiService
    name: wlan0
    parameters:
        snapshot: net
    keywords:
        WIFI_MODE: ACCESS_POINT
        WIFI_SECURITY: WPA2
        WIFI_PASSWORD: testKEYS

- service:
    type: WirepasSink
    name: sink1
    parameters:
        snapshot: wirepas-sink
        plugin: WirepasConfigurationService.dp
        system: wirepasSink1
        start: True
    keywords:
        NETWORK_ID: 10450204
        NETWORK_CHANNEL: 10
        ADDRESS: 2

- service:
    type: WirepasSink
    name: sink2
    parameters:
        snapshot: wirepas-sink
        plugin: WirepasConfigurationService.dp
        system: wirepasSink2
        start: True
    keywords:
        NETWORK_ID: 10450204
        NETWORK_CHANNEL: 10
        ADDRESS: 4
        
- service:
    type: WirepasTransport
    name: wirepas-cloud
    parameters:
        snapshot: wirepas-transport
        plugin: WirepasConfigurationService.dp
        ta_system=wirepasTransport1
        tb_system=wirepasTransport2
        ms_system=wirepasMicro
        start: True
    keywords:
        TA-ENABLE: True
        TA-SECURE: True
        TA-ADDRESS: solidrunwpewnt.extwirepas.com
        TA-PORT: 8883
        TA-USER: mosquittouser
        TA-PASSWORD: peWVOA8qisIvBQYt6LkVJKCusVJl
        TB-ENABLE: False
        MS-ENABLE: False
